// Generated by CoffeeScript 1.12.5
(function() {
  var partial,
    slice = [].slice;

  module.exports = partial = function() {
    var args, fun;
    fun = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    return function() {
      var args2;
      args2 = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return fun.apply(this, args.concat(args2));
    };
  };

}).call(this);
