// Generated by CoffeeScript 1.12.7
(function() {
  var PouchDB, browser, location;

  PouchDB = require('pouchdb-browser');

  location = function(name) {
    return [window.location.protocol, '//', window.location.host, '/', name].join('');
  };

  browser = function(month) {
    var name;
    name = ['reference', month].join('-');
    return new PouchDB(location(name));
  };

  module.exports = {
    browser: browser
  };

}).call(this);
